// Central repository for all hardcoded mock data used across the Superadmin module.
// All fields are aligned to match their respective TypeScript interfaces exactly.

// Matches: OwnerDirectoryItem (which extends OwnerProfile + BaseEntity)
export const MOCK_OWNERS = [
  {
    id: '1',
    userId: 'user1',
    name: 'Satya Prakash',
    email: 'satya@spgplatform.com',
    phone: '9876543210',
    businessName: 'Satya PGs',
    city: 'Bangalore',
    address: '123 Tech Park, Whitefield',
    gst: '29ABCDE1234F1Z5',
    pan: 'ABCDE1234F',
    expectedPgs: 5,
    expectedBeds: 200,
    status: 'Active',
    planId: 'p2',
    propertiesCount: 5,
    bedsCount: 200,
    occupancy: 142,
    collectionThisMonth: 500000,
    lastLogin: '2024-03-15T10:30:00Z',
    createdAt: '2023-01-15T00:00:00Z',
    updatedAt: '2024-03-15T00:00:00Z',
    createdBy: 'system',
    updatedBy: 'system',
    isDeleted: false,
  },
  {
    id: '2',
    userId: 'user2',
    name: 'Rahul Sharma',
    email: 'rahul@sharmaHomes.in',
    phone: '9876543211',
    businessName: 'Sharma Homes',
    city: 'Mumbai',
    address: '456 Andheri West, Mumbai',
    gst: '27FGHIJ5678K2L3',
    pan: 'FGHIJ5678K',
    expectedPgs: 2,
    expectedBeds: 50,
    status: 'Active',
    planId: 'p1',
    propertiesCount: 2,
    bedsCount: 50,
    occupancy: 45,
    collectionThisMonth: 150000,
    lastLogin: '2024-03-14T08:20:00Z',
    createdAt: '2023-03-10T00:00:00Z',
    updatedAt: '2024-03-14T00:00:00Z',
    createdBy: 'system',
    updatedBy: 'system',
    isDeleted: false,
  },
  {
    id: '3',
    userId: 'user3',
    name: 'Amit Kumar',
    email: 'amit@amitStays.com',
    phone: '9876543212',
    businessName: 'Amit Stays',
    city: 'Pune',
    address: '789 Hinjewadi Phase 2, Pune',
    expectedPgs: 1,
    expectedBeds: 25,
    status: 'Inactive',
    planId: 'p1',
    propertiesCount: 1,
    bedsCount: 25,
    occupancy: 18,
    collectionThisMonth: 60000,
    lastLogin: '2024-02-10T14:00:00Z',
    createdAt: '2023-05-22T00:00:00Z',
    updatedAt: '2024-02-10T00:00:00Z',
    createdBy: 'system',
    updatedBy: 'system',
    isDeleted: false,
  },
  {
    id: '4',
    userId: 'user4',
    name: 'Priya Nair',
    email: 'priya@nairPG.com',
    phone: '9876543213',
    businessName: 'Nair PG House',
    city: 'Hyderabad',
    address: '321 Gachibowli, Hyderabad',
    gst: '36MNOPQ9012R3S4',
    pan: 'MNOPQ9012R',
    expectedPgs: 3,
    expectedBeds: 120,
    status: 'Active',
    planId: 'p3',
    propertiesCount: 3,
    bedsCount: 120,
    occupancy: 98,
    collectionThisMonth: 320000,
    lastLogin: '2024-03-16T09:00:00Z',
    createdAt: '2023-07-01T00:00:00Z',
    updatedAt: '2024-03-16T00:00:00Z',
    createdBy: 'system',
    updatedBy: 'system',
    isDeleted: false,
  },
];

// Matches: OwnerRequest (which extends BaseEntity)
export const MOCK_REQUESTS = [
  {
    id: 'req1',
    name: 'Vikram Singh',
    email: 'vikram@example.com',
    phone: '9123456780',
    businessName: 'Singh PG',
    city: 'Delhi',
    pgCount: 1,
    bedCount: 30,
    status: 'Pending',
    planId: 'p2',
    message: 'Interested in Premium plan. Looking to onboard ASAP.',
    createdAt: '2024-03-15T10:30:00Z',
    updatedAt: '2024-03-15T10:30:00Z',
    createdBy: 'public',
    updatedBy: 'public',
    isDeleted: false,
  },
  {
    id: 'req2',
    name: 'Priya Patel',
    email: 'priya@example.com',
    phone: '9123456781',
    businessName: 'Patel Girls Hostel',
    city: 'Ahmedabad',
    pgCount: 2,
    bedCount: 100,
    status: 'Pending',
    planId: 'p1',
    message: 'Wants a demo before signing up.',
    createdAt: '2024-03-14T14:20:00Z',
    updatedAt: '2024-03-14T14:20:00Z',
    createdBy: 'public',
    updatedBy: 'public',
    isDeleted: false,
  },
  {
    id: 'req3',
    name: 'Neha Gupta',
    email: 'neha@example.com',
    phone: '9123456782',
    businessName: 'Gupta Residency',
    city: 'Chennai',
    pgCount: 3,
    bedCount: 150,
    status: 'Approved',
    planId: 'p3',
    message: 'Documentation has been submitted.',
    createdAt: '2024-03-12T09:15:00Z',
    updatedAt: '2024-03-13T11:00:00Z',
    createdBy: 'public',
    updatedBy: 'admin',
    isDeleted: false,
  },
  {
    id: 'req4',
    name: 'Suresh Babu',
    email: 'suresh@example.com',
    phone: '9123456783',
    businessName: 'Babu Lodge',
    city: 'Coimbatore',
    pgCount: 1,
    bedCount: 20,
    status: 'Hold',
    planId: 'p1',
    message: 'GST documents pending.',
    createdAt: '2024-03-10T11:00:00Z',
    updatedAt: '2024-03-11T10:00:00Z',
    createdBy: 'public',
    updatedBy: 'admin',
    isDeleted: false,
  },
];

// Matches: SuperAdminPlan
export const MOCK_PLANS = [
  {
    id: 'p1',
    name: 'Basic',
    price: 999,
    maxProperties: 1,
    maxBeds: 50,
    maxStaff: 2,
    features: ['tenant_management', 'basic_reports', 'email_support'],
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2023-01-01T00:00:00Z',
    createdBy: 'system',
    updatedBy: 'system',
    isDeleted: false,
  },
  {
    id: 'p2',
    name: 'Premium',
    price: 2499,
    maxProperties: 5,
    maxBeds: 500,
    maxStaff: 10,
    features: ['tenant_management', 'advanced_reports', 'payment_gateway', 'staff_logins', 'priority_support'],
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2023-01-01T00:00:00Z',
    createdBy: 'system',
    updatedBy: 'system',
    isDeleted: false,
  },
  {
    id: 'p3',
    name: 'Enterprise',
    price: 4999,
    maxProperties: 999,
    maxBeds: 9999,
    maxStaff: 999,
    features: ['unlimited_properties', 'white_labeling', 'dedicated_support', 'custom_integrations', 'api_access'],
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2023-01-01T00:00:00Z',
    createdBy: 'system',
    updatedBy: 'system',
    isDeleted: false,
  },
];

// Matches: SuperAdminTicket
export const MOCK_TICKETS = [
  {
    id: 't1',
    title: 'Payment Gateway Issue',
    description: 'Students cannot pay rent via UPI. Error: "Payment declined" even for valid UPI IDs.',
    status: 'Open',
    priority: 'High',
    ownerId: '1',
    createdAt: '2024-03-15T09:00:00Z',
    updatedAt: '2024-03-15T09:00:00Z',
    createdBy: '1',
    updatedBy: '1',
    isDeleted: false,
  },
  {
    id: 't2',
    title: 'How to add a 6th property?',
    description: 'The system shows an error when I try to add a new property. I am on the Premium plan which allows 5.',
    status: 'In Progress',
    priority: 'Medium',
    ownerId: '1',
    createdAt: '2024-03-14T10:00:00Z',
    updatedAt: '2024-03-15T08:00:00Z',
    createdBy: '1',
    updatedBy: 'admin',
    isDeleted: false,
  },
  {
    id: 't3',
    title: 'App crashing on iOS',
    description: 'The manager companion app crashes on iOS 17 immediately after login.',
    status: 'Resolved',
    priority: 'High',
    ownerId: '2',
    createdAt: '2024-03-10T14:00:00Z',
    updatedAt: '2024-03-12T11:00:00Z',
    createdBy: '2',
    updatedBy: 'admin',
    isDeleted: false,
  },
  {
    id: 't4',
    title: 'Report download not working',
    description: 'The monthly rent collection report fails to download. Browser shows a 504 error.',
    status: 'Open',
    priority: 'Low',
    ownerId: '4',
    createdAt: '2024-03-16T07:30:00Z',
    updatedAt: '2024-03-16T07:30:00Z',
    createdBy: '4',
    updatedBy: '4',
    isDeleted: false,
  },
];

// Matches: SuperAdminAuditLog
export const MOCK_AUDIT_LOGS = [
  {
    id: 'log1',
    action: 'OWNER_REQUEST_APPROVED',
    actorId: 'superadmin',
    targetId: 'req3',
    details: 'Approved owner request for Neha Gupta (Gupta Residency)',
    createdAt: '2024-03-13T11:05:00Z',
  },
  {
    id: 'log2',
    action: 'PLAN_UPDATED',
    actorId: 'superadmin',
    entityId: 'p2',
    entity: 'plan',
    details: 'Updated Premium plan price from Rs.1999 to Rs.2499',
    createdAt: '2024-03-12T14:30:00Z',
  },
  {
    id: 'log3',
    action: 'OWNER_STATUS_CHANGED',
    actorId: 'superadmin',
    targetId: '3',
    details: 'Changed status of Amit Kumar to Inactive',
    createdAt: '2024-03-11T10:20:00Z',
  },
  {
    id: 'log4',
    action: 'OWNER_REQUEST_HOLD',
    actorId: 'superadmin',
    targetId: 'req4',
    details: 'Put request from Suresh Babu on hold — GST documents pending',
    createdAt: '2024-03-11T10:00:00Z',
  },
  {
    id: 'log5',
    action: 'SETTINGS_UPDATED',
    actorId: 'superadmin',
    details: 'Updated platform support email to support@spgplatform.com',
    createdAt: '2024-03-10T09:00:00Z',
  },
  {
    id: 'log6',
    action: 'ADMIN_LOGIN',
    actorId: 'superadmin',
    details: 'Superadmin logged in from IP 192.168.1.10',
    createdAt: '2024-03-10T08:55:00Z',
  },
];

// Dashboard Stats - NOTE: field names MUST match SuperAdminDashboardData interface exactly
// SuperAdminDashboardData expects: mrr (not monthlyRecurringRevenue)
export const MOCK_DASHBOARD_STATS = {
  activeOwnersCount: 42,
  pendingRequestsCount: 8,
  activePropertiesCount: 156,
  totalStudentsCount: 3420,
  occupancyPercentage: 85,
  mrr: 1250000,               // field name matches SuperAdminDashboardData.mrr
  openTicketsCount: 12,
  expiringPlansCount: 5,
  latestRequests: MOCK_REQUESTS,
  recentAuditLogs: MOCK_AUDIT_LOGS,
  ownersByPlan: [
    { plan: 'Basic', count: 20 },
    { plan: 'Premium', count: 15 },
    { plan: 'Enterprise', count: 7 },
  ],
  revenueByMonth: [
    { month: 'Oct', revenue: 950000 },
    { month: 'Nov', revenue: 1020000 },
    { month: 'Dec', revenue: 1100000 },
    { month: 'Jan', revenue: 1080000 },
    { month: 'Feb', revenue: 1150000 },
    { month: 'Mar', revenue: 1250000 },
  ],
};
